# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'qi'

#google-ID: 'UA-135279548-1'

menu:
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/zongshuai818'}
- {icon: 'twitter', link: 'https://twitter.com/Zach_Qi'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/daniel-daza-8229b5141//'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Previous'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
